### ISSUE TITLE
TN: Creating 'Purpose Built' Accounts at-boot within a testnet

### ISSUE THREAD

**Issue by relativityboy** [steemit/tinman#111]
As a developer using the testnet I may want an easy way to create an account or accounts with certain properties so I can write, test, and experiment on my application with high time-efficiency. 

TLDR: Create accounts in a testnet with certain pre-defined properties.

**AC**
- [x] discussion in comments of what the capabilities should be
- [x] `# Results` describing conclusions of a 1st pass MVP

**Comment by bnchdrff** [comment]
i like the paradigm of a package's test suite handling any relevant account creation, as seen in dsteem: https://github.com/steemit/dsteem/blob/master/test/common.ts#L53

**Comment by relativityboy** [comment]
@bnchdrff - that's cool, but what features does the package's test suite need?

**Comment by roadscape** [comment]
A few approaches come to mind:
1. create a service which creates testnet accounts (e.g. https://github.com/steemit/dsteem/blob/master/test/common.ts#L41)
2. give devs private keys so they can create accounts manually
3. have devs create mainnet dev accounts which can then be re-used on testnet

The benefit of (1) is that any dev can use it (easy to use, slightly harder to abuse).
The problem with (2) is that the private keys need to stay internal (otherwise abusable).
The benefit of (3) is that it doesn't require any additional tooling.

**Comment by relativityboy** [comment]
We need this, and its solution,  in the 1st week of sprint 15.

**Comment by inertia186** [comment]
# Results

We will create custom accounts defined in a config file.

**Comment by relativityboy** [comment]
^^ most lip-service `# Results` ever.
