### ISSUE TITLE
Increase unit testing coverage in Tinman

### ISSUE THREAD

**Issue by relativityboy** [steemit/tinman#115]
As a user of tinman I want to have confidence that it will perform all its advertised operations _so that [my time waiting for a blockchain *net to spool up](https://xkcd.com/303/) isn't a waste of time._

**AC**
- [x] unit test framework in place
- [x] 3 critical components tested
- [x] `# Results` listing which components  are tested

**Comment by inertia186** [comment]
# Results

* `txgen` - The refactor from #106 allows us to do deep testing.
* `util` - @theoreticalbts provided a bunch of documentation that could be directly translated into tests, except in `iterate_operations_from`, which needed to be translated to the new canonical operations.
* `keysub` - Mostly stubbed because it relies upon external executables that need mockups.
