### ISSUE TITLE
TN: txgen & submit - add support for command type & subtypes in .actions file

### ISSUE THREAD

**Issue by relativityboy** [steemit/tinman#124]
As a user of tinman, I want a way to put arbitrary metadata object (MO) into an actions output stream, and have it consumed and either ignored or used in a constructive way by submit. The Command type will be created to support this.

**Supporting Materials**
* The MO should be a json object
* MO should declare itself as such if necessary 
* MO should describe its function. For this story at least these types 
  * `txgen:semver` <- the version of txgen that created the file
  * `epoch:created` <- the second the actions file was created
  * `actions:count` <- the total number of actons in this file (does not include waitblocks)
  * `comment` <- generic comment
  * `recommend:waitblocks` <- might be in addition to *txgen:transactions_per_block* below

**AC**
- [x] txgen has semver variable created at `0.1.0`
- [x] describe the json structure in a `# Results` comment.
- [x] txgen output stream's 1st line is MO with txgen semver
- [x] txgen output stream's 2nd line is MO with epoch date
- [x] submit consumes MO and, at a minimum, outputs MO information to log/shell. Otherwise performs some action based on MO's described function & properties.

**Comment by inertia186** [comment]
I'm thinking we need this before implementing #103.  Since we use `submit` for `gatling` as well as `txgen`, I think we want to make sure `submit` will still blindly pass along transactions in one situation and not the other:

* For `gatling`, we *want* `submit` to blindly pass along transactions.
* For `txgen` we *do not want* `submit` to blindly pass along transactions.  Why?  Because `submit` must now be aware that it is bootstraping the blockchain.  Before, bootstrapping directives were `txgen`'s job by declaring the `miss_blocks` parameter of the `wait_block` command.  Now, that data is basically a guideline unless mainnet has progressed close-to or far-enough beyond `miss_blocks`.

Therefore, the way `submit` knows how to behave will depend on the presense of certain MO parameters (epoch date).  If this certain MO is not present, `submit` is bootstrapping.  If not, blindly pass transactions.

---

I'd also suggest the following MO types:
* `txgen:transactions_per_block` <- typically `40`, can be ignored by `submit`
* `txgen:origin_api` <- typically `https://api.steemit.com`, used to help determine how stale the `.actions` are by looking at the `head_block_num` of the origin.
* `txgen:origin_head_block_num` <- set when `.actions` begin being generated.

**Comment by inertia186** [comment]
# Result

`snapshot`

```json
{"metadata": {
  "snapshot:semver": "0.1",
  "snapshot:origin_api": "http://calculon.local"
}}
```

`txgen`

```json
["metadata",{
  "actions:count":4000,
  "epoch:created":"2018-09-26 04:46:36.041271",
  "recommend:miss_blocks":28776730,
  "snapshot:origin_api":"http://calculon.local",
  "snapshot:semver":"0.1",
  "txgen:semver":"0.1",
  "txgen:transactions_per_block":40
}]
```

**Comment by relativityboy** [comment]
Suggest `txgen:transactions_per_block` -> `recommend:transactions_per_bloc`

**Comment by relativityboy** [comment]
Merged to `develop`
