### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by bobinson** [steemit/tinman#59]
1. using Python 3.6.4
2. followed the instructions

Error received while trying pip install ./tinman

```
 Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/tinman.egg-info
    writing pip-egg-info/tinman.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/tinman.egg-info/dependency_links.txt
    writing entry points to pip-egg-info/tinman.egg-info/entry_points.txt
    writing top-level names to pip-egg-info/tinman.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/tinman.egg-info/SOURCES.txt'
    package init file 'tinman/simple_steem_client/__init__.py' not found (or not a regular file)
    error: package directory 'tinman/simple_steem_client/simple_steem_client' does not exist
    
```

**Comment by sndp487** [comment]
The issue is that there is a symlink kind of folder inside ~/src/tinman/tinman/simple_steem_client which clone command is not downloading. Do the following to fix:-
1. cd ~/src/tinman/tinman/simple_steem_client
2. git clone https://github.com/steemit/simple_steem_client.git
3. cd ~/src/tinman
4. pip install .

**Comment by bobinson** [comment]
Thank you @sndp487  this will be helpful.

**Comment by inertia186** [comment]
Since they're both public repos, we should reverse #35.
