### ISSUE TITLE
Gatling: Stream transactions from one Steem chain to a Testnet 

### ISSUE THREAD

**Issue by relativityboy** [steemit/tinman#65]
As a blockchain developer I want to be able to stream transactions from Steem's **Mainnet** into a Steem **Testnet** of my choosing so that I can see how it performs under a production-like loads

**AC**
- [x] create a sub-component of Tinman called Gatling
- [x] Gatling should be able to read transactions from any node on Steem's Mainnet in "realtime"
- [x] Gatling should be able to transform those transactions into valid transactions on any testnet for which it has a valid auth to re-sign those transactions.
- [x] Gatling should be able to accept information needed via config or consol so it can re-sign those transactions
- [x] Gatling should be able to stop at a specific block number or continue indefinitely
- [x] documentation for using Gatling is provided in this repo in an appropriate `.md` file, referenced from any applicable TOC.
- [x] A comment called `# Results` outlines gatling's general philosophy (may be copied from .md file ) and any 'soft' design decisions that may have assumptions embedded in them.

**Comment by inertia186** [comment]
To stream from the last irreversible block:

```bash
tinman gatling -s https://api.steemit.com -o -
```

**Comment by inertia186** [comment]
5fd3346b5a291a07bc6de8b16fa498ed15180477

**Comment by relativityboy** [comment]
Assigning 8 points now, can be modded to higher points later as this is both a spike and an executable.

**Comment by inertia186** [comment]
# Result

Originally `tinman port` was going to watch mainnet and send speicifc operation types over to testnet. 
 Those operation type names have changed since then and the scope of operations has expanded:

https://github.com/steemit/tinman/commit/07044c20ac12095bc68da993a867bef574d83567#diff-c58e95a1257e722b056cf95c85d5d9b7L17-L22

Also needed to tweak `util.py` to look at the new json form:

https://github.com/steemit/tinman/commit/07044c20ac12095bc68da993a867bef574d83567#diff-fdd5e0ea05c4c25c771becff9d0903c8R124
