### ISSUE TITLE
TN: Gatling - retry reading Mainnet on errors

### ISSUE THREAD

**Issue by relativityboy** [steemit/tinman#70]
As a user of gatling, I want it to not die, and to retry trivial errors when reading from Mainnet

**AC**
- [x] gatling retries trivial errors
- [ ] ~gatling outputs those errors to a log~
- [x] gatling outputs those errors `stderr`
- [x] A `# Results` comment listing the errors gatling will retry

**Comment by inertia186** [comment]
# Result

Errors retried:

* `Unable to acquire database lock`
* `Internal Error`
* `Server error`
* `Upstream response error`

I've observed `Internal Error` while testing this code.  I have seen `Unable to acquire database lock` from `gatling` in the past, but not while testing this code.  `Server error` and `Upstream response error` are included because if `gatling` can start successfully, then encountered `Server error` or `Upstream response error`, they should be recoverable.

Also, there's a maximum of 30 retries, which is reset after every success.
