### ISSUE TITLE
TN: Gatling: make transfers a ratio of Mainnet (therefore more reliable)

### ISSUE THREAD

**Issue by relativityboy** [steemit/tinman#92]
As a testnet, I want traffic coming from Mainnet to succeed, and for my traffic to follow Mainnet's over time. Gatling should adjust the amount of all transfers to reflect the ratio of tokens on testnet to the ratio of tokens on Mainnet so that the transactions do not fail on Testnet due to incorrect funds, particularly over time.

**AC**
- [ ] ~gatling adjusts transfer operations appropriately.~
- [ ] ~optional - gatling is able to adjust other claim operations if necessary.~
- [x] make this its own module

**Comment by inertia186** [comment]
Let's look at this the way it works now.  On the mainnet, `dynamic_global_properties.total_vesting_fund_steem`:

`194440984.130 STEEM`

While on testnet, `dynamic_global_properties.total_vesting_fund_steem`:

`36485445.835 TESTS`

This means that when someone makes a transfer on mainnet, and gatling ports it over to testnet, that transfer has over 5 times the impact than it did on mainnet.

You might think the solution is to figure out the ratio and just transform a mainnet amount to a proportional testnet amount.

E.g., if alice sends a transfer to bob in the amount of `5.000 STEEM`, we should interpret that as `0.938 TESTS`.  So far so good.

One problem is when alice transfer `0.001 STEEM`.  We cannot use the same formula because that would require more precision.

**Comment by inertia186** [comment]
I think this should be its own module.  See: d6a80d867206e424f802849d993a785484439436

Similar vein to `keysub`, I called it `amountsub`.  You use it like this:

```bash
#!/bin/bash

( \
  echo "[\"set_secret\", {\"secret\":\"$SHARED_SECRET\"}]" ; \
  tinman gatling -o - \
) | \
tinman amountsub --floor-satoshi 1 --ratio 0.187 | \
tinman keysub --get-dev-key ~/src/steem/build_tn/programs/util/get_dev_key | \
tinman submit --realtime -t http://127.0.0.1:18751 \
    --signer ~/src/steem/build_tn/programs/util/sign_transaction \
    --realtime \
    --fail fail.json
    --timeout 600
```

With `--floor-satoshi`, we're saying that if the result went below 1, it's 1, but this rule *won't* change `{"amount" : "0"}` to `{"amount" : "1"}`.

**Comment by inertia186** [comment]
Placed this into "in progress" because the spirit of the issue is being addressed, but not in `gatling`:

https://github.com/steemit/tinman/compare/92-amountsub

The functionality is in its own module.  It adjusts *all* `amount` values proportional to `--ratio` and works with pipes so that it can be part of `gatling`, a dedicated price feed modile, or even `txgen` (if we wanted to try removing proportionality from `txgen` for some reason).

**Comment by inertia186** [comment]
Also, #99 is related because we can extract proportionality to its own method then call it from `port_snapshot`.
